export const version = '__VERSION__' as const;

export {
  Base,
  getInstances,
  type BaseAsyncConstructor,
  type BaseChildren,
  type BaseConfig,
  type BaseConfigComponents,
  type BaseConstructor,
  type BaseEl,
  type BaseOptions,
  type BaseProps,
  type BaseRefs,
  type Managers,
} from './Base/index.js';
export { type BaseDecorator, type BaseEventHookParams, type BaseInterface } from './Base/types.js';
export {
  getScopedGroups,
  withBreakpointManager,
  withBreakpointObserver,
  withDrag,
  withExtraConfig,
  withFreezedOptions,
  withGroup,
  withIntersectionObserver,
  withMountOnMediaQuery,
  withMountWhenInView,
  withMountWhenPrefersMotion,
  withMutation,
  withName,
  withRelativePointer,
  withResponsiveOptions,
  withScrolledInView,
  type DragDecoratorOptions,
  type MutationDecoratorOptions,
  type NormalizedOffset,
  type OffsetValue,
  type RelativePointerDecoratorOptions,
  type RelativePointerInterface,
  type ScrollInViewProps,
  type WithBreakpointObserverInterface,
  type WithBreakpointObserverProps,
  type WithDragInterface,
  type WithFreezedOptionsInterface,
  type WithGroupInterface,
  type WithGroupOptions,
  type WithGroupProps,
  type WithIntersectionObserverInterface,
  type WithIntersectionObserverProps,
  type WithMountWhenInViewInterface,
  type WithMountWhenInViewProps,
  type WithMutationInterface,
  type WithScrolledInViewInterface,
  type WithScrolledInViewOptions,
  type WithScrolledInViewProps,
  type withMountOnMediaQueryInterface,
  type withMountOnMediaQueryProps,
} from './decorators/index.js';
export {
  closestComponent,
  createApp,
  defineFeatures,
  getClosestParent,
  getDirectChildren,
  getInstanceFromElement,
  importOnInteraction,
  importOnMediaQuery,
  importWhenIdle,
  importWhenPrefersMotion,
  importWhenVisible,
  isDirectChild,
  logTree,
  queryComponent,
  queryComponentAll,
  registerComponent,
  registerComponents,
  type CreateAppOptions,
  type QueryOptions,
} from './helpers/index.js';
export {
  AbstractService,
  DragService,
  KeyService,
  LoadService,
  MutationService,
  PointerService,
  RafService,
  ResizeService,
  ScrollService,
  useDrag,
  useKey,
  useLoad,
  useMutation,
  usePointer,
  useRaf,
  useResize,
  useScroll,
  type DragServiceInterface,
  type DragServiceOptions,
  type DragServiceProps,
  type KeyServiceInterface,
  type KeyServiceProps,
  type LoadServiceInterface,
  type LoadServiceProps,
  type MutationServiceInterface,
  type MutationServiceOptions,
  type MutationServiceProps,
  type PointerServiceInterface,
  type PointerServiceProps,
  type RafServiceInterface,
  type RafServiceProps,
  type ResizeServiceInterface,
  type ResizeServiceProps,
  type ScrollServiceInterface,
  type ScrollServiceProps,
  type ServiceConfig,
  type ServiceInterface,
} from './services/index.js';
