name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  dashdoc:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci && brew install dashing

      - name: Build Typedoc
        run: npm run build:typedoc --workspace=@studiometa/js-toolkit-docs

      - name: Build Dash docset
        run: |
          cd packages/docs/docs/
          cp ../dashing.json .
          dashing build
          tar --exclude='.DS_Store' -zcvf studiometa-js-toolkit.docset.tgz studiometa-js-toolkit.docset

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: studiometa-js-toolkit.docset.tgz
          path: packages/docs/docs/studiometa-js-toolkit.docset.tgz

  release:
    runs-on: ubuntu-latest
    needs:
      - dashdoc
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 15
          registry-url: https://registry.npmjs.org/

      - run: npm ci

      - run: npm run build

      - name: Test
        run: npm run test -- -- --coverage || npm run test -- -- --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage
          flags: unittests
          fail_ci_if_error: false
          path_to_write_report: ./codecov_report.txt
          verbose: true

      - run: cd dist && ls -al && npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

      # @see https://github.com/actions/create-release/issues/38#issuecomment-715327220
      # @see https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files
      - name: Prepare the changelog from the tag message
        id: prepare_changelog
        run: |
          # Parse version
          VERSION=${GITHUB_REF/refs\/tags\//}
          echo "Setting release version to $VERSION"
          echo "release_version=$VERSION" >> $GITHUB_ENV

          # Parse tag message
          CHANGELOG=$(git for-each-ref $GITHUB_REF | tail -n+3)

          echo $CHANGELOG

          # Set markdown titles
          CHANGELOG=${CHANGELOG/Added/## Added}
          CHANGELOG=${CHANGELOG/Fixed/## Fixed}
          CHANGELOG=${CHANGELOG/Changed/## Changed}
          CHANGELOG=${CHANGELOG/Removed/## Removed}
          CHANGELOG=${CHANGELOG/Deprecated/## Deprecated}
          CHANGELOG=${CHANGELOG/Security/## Security}

          echo $CHANGELOG

          # Remove PGP signature
          CHANGELOG="${CHANGELOG%-----BEGIN*}"

          echo $CHANGELOG

          # Change linebreaks and other special characters
          CHANGELOG="${CHANGELOG//'%'/'%25'}"
          CHANGELOG="${CHANGELOG//$'\n'/'%0A'}"
          CHANGELOG="${CHANGELOG//$'\r'/'%0D'}"

          echo "Setting changelog body to:"
          echo $CHANGELOG

          echo 'changelog<<EOF' >> $GITHUB_ENV
          echo $CHANGELOG >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: studiometa-js-toolkit.docset.tgz
          path: packages/docs/docs/studiometa-js-toolkit.docset.tgz

      # @see https://github.com/actions/create-release
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref }}
          name: v${{ env.release_version }}
          body: ${{ env.changelog }}
          draft: false
          prerelease: false
          files: packages/docs/docs/studiometa-js-toolkit.docset.tgz
